version: "3.5"

services:
  postgres:
    image: library/postgres:10.7
    container_name: db
    restart: unless-stopped 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloakdb
    ports:
      - 5432:5432

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: 260
      KEYCLOAK_MANAGEMENT_PASSWORD: 260
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_CREATE_ADMIN_USER: 'true'
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_HTTP_PORT: 3033
      KEYCLOAK_HTTPS_PORT: 3034
      KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      KEYCLOAK_CACHE_OWNERS_COUNT: 3
      KEYCLOAK_AUTH_CACHE_OWNERS_COUNT: 3
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:3033
      # - ${KEYCLOAK_PORT:-8443}:8443
